# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roman/Documents/R-Type

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roman/Documents/R-Type

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roman/Documents/R-Type/CMakeFiles /home/roman/Documents/R-Type/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roman/Documents/R-Type/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RTypeClient

# Build rule for target.
RTypeClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RTypeClient
.PHONY : RTypeClient

# fast build rule for target.
RTypeClient/fast:
	$(MAKE) -f CMakeFiles/RTypeClient.dir/build.make CMakeFiles/RTypeClient.dir/build
.PHONY : RTypeClient/fast

#=============================================================================
# Target rules for targets named RTypeServer

# Build rule for target.
RTypeServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RTypeServer
.PHONY : RTypeServer

# fast build rule for target.
RTypeServer/fast:
	$(MAKE) -f CMakeFiles/RTypeServer.dir/build.make CMakeFiles/RTypeServer.dir/build
.PHONY : RTypeServer/fast

Client/src/main.o: Client/src/main.cpp.o

.PHONY : Client/src/main.o

# target to build an object file
Client/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/RTypeClient.dir/build.make CMakeFiles/RTypeClient.dir/Client/src/main.cpp.o
.PHONY : Client/src/main.cpp.o

Client/src/main.i: Client/src/main.cpp.i

.PHONY : Client/src/main.i

# target to preprocess a source file
Client/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/RTypeClient.dir/build.make CMakeFiles/RTypeClient.dir/Client/src/main.cpp.i
.PHONY : Client/src/main.cpp.i

Client/src/main.s: Client/src/main.cpp.s

.PHONY : Client/src/main.s

# target to generate assembly for a file
Client/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/RTypeClient.dir/build.make CMakeFiles/RTypeClient.dir/Client/src/main.cpp.s
.PHONY : Client/src/main.cpp.s

Server/src/main.o: Server/src/main.cpp.o

.PHONY : Server/src/main.o

# target to build an object file
Server/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/RTypeServer.dir/build.make CMakeFiles/RTypeServer.dir/Server/src/main.cpp.o
.PHONY : Server/src/main.cpp.o

Server/src/main.i: Server/src/main.cpp.i

.PHONY : Server/src/main.i

# target to preprocess a source file
Server/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/RTypeServer.dir/build.make CMakeFiles/RTypeServer.dir/Server/src/main.cpp.i
.PHONY : Server/src/main.cpp.i

Server/src/main.s: Server/src/main.cpp.s

.PHONY : Server/src/main.s

# target to generate assembly for a file
Server/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/RTypeServer.dir/build.make CMakeFiles/RTypeServer.dir/Server/src/main.cpp.s
.PHONY : Server/src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RTypeServer"
	@echo "... RTypeClient"
	@echo "... Client/src/main.o"
	@echo "... Client/src/main.i"
	@echo "... Client/src/main.s"
	@echo "... Server/src/main.o"
	@echo "... Server/src/main.i"
	@echo "... Server/src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

